### ISSUE TITLE
/tmp directory needed

### ISSUE THREAD

**Issue by willemsst** [delitescere/docker-zulu#7]
I'm using the jdk:8 docker image. Dockerfile below.

Yesterday I made a new build and suddenly my system wouldn't start anymore. This is the truncated stacktrace:

```
java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createTempFile(File.java:2024)
    at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.createMimeConfig(MultiPartReaderClientSide.java:143)
    at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.<init>(MultiPartReaderClientSide.java:125)
    at org.glassfish.jersey.media.multipart.internal.MultiPartReaderServerSide.<init>(MultiPartReaderServerSide.java:81)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1350)
    at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:271)
    at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:365)
    at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
    at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
    at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:71)
    at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
    at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
    at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:122)
    at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
    at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
    at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:58)
```

So Jersey is trying to make a temp file while booting. I noticed you remove the tmp directory, and I understand why, but you probably need to add a new empty one after that. At least, that's how I fixed it.

This was my dockerfile

```
FROM delitescere/jdk:8

RUN apk update && \
    apk add bash wget

RUN apk add --update ca-certificates && \
    rm -rf /var/cache/apk/* /tmp/*

RUN update-ca-certificates

# install new relic server monitoring

RUN mkdir /.newrelic && \
    mkdir /etc/newrelic && \
    mkdir /var/log/newrelic
RUN addgroup -g 999 newrelic && adduser -D  -G newrelic -s /bin/false -u 999 newrelic

RUN chown newrelic:newrelic /.newrelic && \
    chown newrelic:newrelic /etc/newrelic/ && \
    chown newrelic:newrelic /var/log/newrelic && \
    chmod 600 /etc/newrelic/

RUN wget -O newrelic.tar.gz https://download.newrelic.com/server_monitor/release/newrelic-sysmond-2.3.0.129-linux.tar.gz && \
    tar xvfz newrelic.tar.gz && \
    mv newrelic-sysmond-*-linux newrelic
RUN cp newrelic/daemon/nrsysmond.x64 /usr/local/bin/nrsysmond && \
    cp newrelic/scripts/nrsysmond-config /usr/local/bin && \
    cp newrelic/nrsysmond.cfg /etc/newrelic/nrsysmond.cfg && \
    rm -rf newrelic && \
    rm -rf newrelic.tar.gz

RUN nrsysmond-config --set license_key=*************
RUN /usr/local/bin/nrsysmond -c /etc/newrelic/nrsysmond.cfg

ENV LANG en_US.utf8

ADD rest-application-0.0.1-SNAPSHOT-all.jar /rest-api.jar

EXPOSE 9090
```

and I added 

```
RUN mkdir -p /tmp
```

to make it work again.

Btw, thank you for providing this docker image!

**Comment by delitescere** [comment]
Fixed with 151034d
